---
format: html
echo: false
warning: false
footer-left: "Made with [surveydown](https://surveydown.org)"
footer-right: '[<i class="bi bi-github"></i> Source Code](https://github.com/surveydown-dev/demos)'
---

```{r}
# pak::pkg_install('sagesteppe/surveydown')
library(surveydown)
```

::: {#numerics_not_saved .sd-page}

# Demo - Leaflet Map

::: {.callout-note}

Numeric values will save to local CSV, but not to Supabase. 

:::

```{r}
sd_question(
  type  = "textarea",
  id    = "paragraph",
  label = "Write a paragraph:"
)
```

```{r}
sd_question(
  type  = 'numeric',
  id    = 'age',
  label = "What's your age?"
)

```

```{r integer apples}
sd_question(type = "slider_numeric", id = 'apples_integer', label = 'integer', option = 0:100)
```

```{r animation}
sd_question(type = "slider_numeric", id = 'apples_animate',  option = seq(0, 100),
                  pre = "$", sep = ",", label = 'apples rule everything around me', step = 25,
                  animate = TRUE)
```

```{r looping animation}
sd_question(type = "slider_numeric", id = 'apples_animation',  label = 'apple_loops',
            option = seq(0, 200, 10), 
            default = 1, step = 40,
                  animate =  shiny::animationOptions(loop = TRUE))
```

```{r decimal apples}
sd_question(type = "slider_numeric", id = 'apples_decimal',  label = 'decimals', option = seq(0, 1, 0.05), default = 0.1)
```

```{r range slider}
sd_question(type = "slider_numeric", id = 'apples_range',  label = 'range', option = seq(0, 1, 0.05), default = c(0.3,0.65))
```

```{r}
sd_next()
```

:::

::: {#end .sd-page}

## End

This it the last page in the survey.

```{r}
sd_close("Exit Survey")
```

:::